// <auto-generated />
using System;
using BudgetBuddy.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetBuddy.Migrations
{
    [DbContext(typeof(BudgetBuddyDbContext))]
    [Migration("20251110132334_InitialCreateWithPasswordReset")]
    partial class InitialCreateWithPasswordReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BudgetBuddy.API.Models.AIRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendationText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AIRecommendations");
                });

            modelBuilder.Entity("BudgetBuddy.API.Models.BudgetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Debt")
                        .HasColumnType("REAL");

                    b.Property<double>("Education")
                        .HasColumnType("REAL");

                    b.Property<double>("Entertainment")
                        .HasColumnType("REAL");

                    b.Property<string>("Financial_Goals")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Going_Out")
                        .HasColumnType("REAL");

                    b.Property<double>("Groceries")
                        .HasColumnType("REAL");

                    b.Property<double>("Healthcare")
                        .HasColumnType("REAL");

                    b.Property<double>("Insurance")
                        .HasColumnType("REAL");

                    b.Property<double>("Investments")
                        .HasColumnType("REAL");

                    b.Property<double>("Loan_Repayment")
                        .HasColumnType("REAL");

                    b.Property<double>("Miscellaneous")
                        .HasColumnType("REAL");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Monthly_Income")
                        .HasColumnType("REAL");

                    b.Property<double>("Monthly_Savings")
                        .HasColumnType("REAL");

                    b.Property<double>("Needs")
                        .HasColumnType("REAL");

                    b.Property<double>("Net_Worth")
                        .HasColumnType("REAL");

                    b.Property<double>("Rent")
                        .HasColumnType("REAL");

                    b.Property<double>("Savings")
                        .HasColumnType("REAL");

                    b.Property<double>("Savings_Investment_Total")
                        .HasColumnType("REAL");

                    b.Property<double>("Subscriptions")
                        .HasColumnType("REAL");

                    b.Property<double>("Total_Expenses")
                        .HasColumnType("REAL");

                    b.Property<double>("Total_Liabilities")
                        .HasColumnType("REAL");

                    b.Property<double>("Travel")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Utilities")
                        .HasColumnType("REAL");

                    b.Property<double>("Wants")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BudgetEntries");
                });

            modelBuilder.Entity("BudgetBuddy.API.Models.FinancialGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CurrentProgress")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TargetAmount")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FinancialGoals");
                });

            modelBuilder.Entity("BudgetBuddy.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BudgetBuddy.API.Models.AIRecommendation", b =>
                {
                    b.HasOne("BudgetBuddy.API.Models.User", "User")
                        .WithMany("AIRecommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetBuddy.API.Models.BudgetEntry", b =>
                {
                    b.HasOne("BudgetBuddy.API.Models.User", "User")
                        .WithMany("BudgetEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetBuddy.API.Models.FinancialGoal", b =>
                {
                    b.HasOne("BudgetBuddy.API.Models.User", "User")
                        .WithMany("FinancialGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BudgetBuddy.API.Models.User", b =>
                {
                    b.Navigation("AIRecommendations");

                    b.Navigation("BudgetEntries");

                    b.Navigation("FinancialGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
